# Main CI pipeline orchestrating build, test, and upload stages
name: Greengage CI

env:
  version: 6

on:
  push:
    tags: ['6.*']   # Trigger on tags for versioned releases
  pull_request:
    branches: ['*'] # Trigger on pull requests for all branches

jobs:
  build:
    strategy:
      fail-fast: true  # Stop on any failure in the matrix
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: write # Required for GHCR access
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-build.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  behave-tests:
    needs: build  # Wait for build to complete
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: read  # Explicit for GHCR access clarity
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-behave.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  regression-tests:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: read  # Explicit for GHCR access clarity
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-regression.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  orca-tests:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: read  # Explicit for GHCR access clarity
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-orca.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  resgroup-tests:
    needs: build
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: read  # Explicit for GHCR access clarity
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-tests-resgroup.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  upload:
    needs: [behave-tests, regression-tests, orca-tests, resgroup-tests]  # Wait for all tests
    strategy:
      fail-fast: true
      matrix:
        target_os: [ubuntu] #, centos]
    permissions:
      contents: read  # Explicit for default behavior
      packages: write # Required for GHCR access
      actions: write  # Required for artifact upload
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-upload.yml@main
    with:
      version: 6
      target_os: ${{ matrix.target_os }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
